# tf-idfを用いたテキスト分類お試し版

In [34]:
from sklearn.datasets import fetch_20newsgroups
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
import numpy as np

categories = ['alt.atheism', 'soc.religion.christian','comp.graphics', 'sci.med', 'rec.sport.baseball']

all_data= fetch_20newsgroups(shuffle=True, categories=categories, random_state=42)


# tfidfによる重み付け
count_vect = CountVectorizer()
X_train_counts = count_vect.fit_transform(all_data.data)

tfidf_transformer = TfidfTransformer()
X_train_tfidf = tfidf_transformer.fit_transform(X_train_counts)

X_train_tfidf.toarray()

all_X = X_train_tfidf
all_y = all_data.target
print(all_X)
print(len(all_data.target))

  (0, 2419)	0.07354874441740068
  (0, 15832)	0.03688832018030732
  (0, 2431)	0.07354874441740068
  (0, 1888)	0.12032418570055538
  (0, 2299)	0.10900327889225868
  (0, 9348)	0.048332462374006985
  (0, 13931)	0.06994000716990036
  (0, 2900)	0.053992915778155334
  (0, 1664)	0.06377083009777801
  (0, 9407)	0.03646441905792654
  (0, 573)	0.07354874441740068
  (0, 10278)	0.03804582438641032
  (0, 38571)	0.05922435885130482
  (0, 35014)	0.04507978225258781
  (0, 25427)	0.06016209285027769
  (0, 8212)	0.05262093755143275
  (0, 6493)	0.06994000716990036
  (0, 10522)	0.04887203612891126
  (0, 25626)	0.06737956734527832
  (0, 5118)	0.07354874441740068
  (0, 7177)	0.06737956734527832
  (0, 24698)	0.04373379014992646
  (0, 35483)	0.056229674798933066
  (0, 12199)	0.030647075984324094
  (0, 16082)	0.025937031978160198
  :	:
  (2853, 26421)	0.11563231803508978
  (2853, 5506)	0.05037505599079204
  (2853, 16402)	0.03490213046360054
  (2853, 35956)	0.06314136146050706
  (2853, 25253)	0.01696339654834809

/Users/e155734/.pyenv/versions/anaconda3-2.5.0/lib/python3.5/site-packages/sklearn/feature_extraction/text.py:1015: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if hasattr(X, 'dtype') and np.issubdtype(X.dtype, np.float):


# novelデータにとっかえてみる

In [1]:
#from sklearn.datasets import fetch_20newsgroups
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
import numpy as np
import math
import os

## 不要な活用語をカットする

In [2]:
# データの中身をlistで入力

file_name = './morpheme_list'
file_list = os.listdir(file_name)
all_datas = []
all_ys = []
count = 0

# 分類ディレクトリを取得
for file in file_list:
    # ディレクトリかどうか判別
    if os.path.isfile(file_name+'/'+file) == True:
        continue
        
    files = os.listdir(str(file_name + '/' + file))
    
    print(file)
    # 分類ごとのnovelデータ取得
    for fil in files:
        print(fil)
        
        fi = str(file_name + '/' + file + '/' + fil)                                
        id = open(fi, 'r') 
        conte = ''
                                    
        ele = fil.split('.')                                                   
        #print(ele[0])  #本のid                                                      
        for contents in id:                                                         
            ele2 = contents.split(',')                                              
            if(ele2[1]!="助詞"):                                                    
                if(ele2[1]!="副詞"):                                                
                    if(ele2[1]!="助動詞"):                                          
                        if(ele2[1]!="記号"):                                        
                            if(ele2[1]!="接続詞"):                                  
                                if(ele2[0]!='——'): 
                                    conte = str(conte + ele2[0] + " ")                                                                         
        # 1nobelごとにlistへ追加
        #print(conte)
        all_datas.append(conte)
        all_ys.append(count)
        
    count = count + 1

910
13204_16876.html.csv
1340_19832.html.csv
16013_30008.html.csv
16033_33773.html.csv
214_20496.html.csv
2310_13554.html.csv
24442_21417.html.csv
2773_8791.html.csv
2824_8914.html.csv
2840_8475.html.csv
2841_8477.html.csv
2842_8479.html.csv
2928_20676.html.csv
2947_48809.html.csv
3600_48333.html.csv
3764_27288.html.csv
42242_16287.html.csv
4243_27740.html.csv
42613_17557.html.csv
43051_15752.html.csv
43452_23665.html.csv
43506_16853.html.csv
43764_18094.html.csv
4431_11291.html.csv
44486_36694.html.csv
44627_37247.html.csv
44718_39337.html.csv
44725_18100.html.csv
44748_39635.html.csv
44749_39636.html.csv
44756_39643.html.csv
44819_42366.html.csv
44834_42340.html.csv
44836_42350.html.csv
44854_42365.html.csv
44894_42270.html.csv
45271_19218.html.csv
45447_35380.html.csv
45454_35421.html.csv
45816_39437.html.csv
45969_22968.html.csv
45970_22967.html.csv
45983_28183.html.csv
46181_34800.html.csv
46310_34748.html.csv
47022_31485.html.csv
47023_39098.html.csv
47092_41596.html.csv
47122_35

In [3]:
#list型からndarray型へ変換
#all_data = np.array([str(a.readline()),str(b.readline()),str(c.readline()),str(d.readline()),str(e.readline()),str(f.readlines()),str(g.readlines()),str(h.readline()),str(i.readline())])
all_data = np.array(all_datas)

# tfidfによる重み付け
count_vect = CountVectorizer()
X_train_counts = count_vect.fit_transform(all_data)

tfidf_transformer = TfidfTransformer(use_idf=True, norm='l2',smooth_idf=True)
#np.set_printoptions(precsion=2)

X_train_tfidf = tfidf_transformer.fit_transform(X_train_counts)
X_train_tfidf.toarray()

all_X = X_train_tfidf
print(all_X)
# list型をndarray型へ変換
#all_y = np.array([0,1,2,3,4,5,6,7,9])
all_y = np.array(all_ys)
print(all_y)

  (0, 156401)	0.007933209718613625
  (0, 113888)	0.008044081317497367
  (0, 169931)	0.008381127998790065
  (0, 44047)	0.009262620593403747
  (0, 163447)	0.011623443024406497
  (0, 125589)	0.016375524773223005
  (0, 28377)	0.010467265272169892
  (0, 147877)	0.016838805929645262
  (0, 136974)	0.00711396497549851
  (0, 169252)	0.014934493837581787
  (0, 115732)	0.006997691624538749
  (0, 218166)	0.010771618051207242
  (0, 19207)	0.004968634576850625
  (0, 195195)	0.005621411762361813
  (0, 215562)	0.017732859377293055
  (0, 197877)	0.009031723879804695
  (0, 133041)	0.014903775127387097
  (0, 146591)	0.006111441820789028
  (0, 205301)	0.012025647456814123
  (0, 230193)	0.01868059422317574
  (0, 165498)	0.015558495235602963
  (0, 32293)	0.0038659615404550893
  (0, 31336)	0.013235511547118984
  (0, 222404)	0.015981152213369636
  (0, 220112)	0.010008819674566146
  :	:
  (8731, 170253)	0.01390338568386555
  (8731, 8780)	0.054295458400599274
  (8731, 24553)	0.021076713385241825
  (8731, 8675)	

/Users/e155734/.pyenv/versions/anaconda3-2.5.0/lib/python3.5/site-packages/sklearn/feature_extraction/text.py:1015: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if hasattr(X, 'dtype') and np.issubdtype(X.dtype, np.float):


# SVM分類

In [4]:
from sklearn.cross_validation import train_test_split
from sklearn.metrics import f1_score
from sklearn import svm
from sklearn.svm import SVC

train_X, test_X, train_y, test_y = train_test_split(all_X, all_y,
                                                    test_size=0.2,
                                                    random_state=42)


clf2 = svm.SVC(kernel='rbf', C=5, gamma=0.2)
clf2.fit(train_X,train_y)
pred_y2 = clf2.predict(test_X)
print(f1_score(test_y, pred_y2, average='macro'))

0.3868905510004991


/Users/e155734/.pyenv/versions/anaconda3-2.5.0/lib/python3.5/site-packages/sklearn/metrics/classification.py:1074: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [5]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(test_y, pred_y2))

[[  2   1   0   1  25   0   0   0   0]
 [  0  80   0   9  23   0   0   0   0]
 [  0   0   9  25   8   0   0   0   0]
 [  0   2   1 714  45   0   0   0   0]
 [  0   5   1  77 581   7   0   0   0]
 [  0   2   0  14  36  28   0   0   0]
 [  0   0   0   6  38   1   1   0   0]
 [  0   0   0   1   2   0   0   0   0]
 [  0   0   0   0   1   1   0   0   0]]
